const $=s=>document.querySelector(s);let expr='',memory=0,angle='DEG',history=JSON.parse(localStorage.getItem('cool-calculator-history')||'[]');
const expressionEl=$('#expression'),resultEl=$('#result'),historyEl=$('#historyList'),memoryStatus=$('#memoryStatus');
function render(){expressionEl.textContent=expr||'0';try{resultEl.textContent=expr?format(calculate(expr)): '0'}catch{resultEl.textContent=expr?'…':'0'};memoryStatus.textContent=memory?'M':'';renderHistory()}
function format(n){if(!Number.isFinite(n))throw Error('Ungültig');if(Math.abs(n)<1e-12)n=0;return Number(n.toPrecision(12)).toLocaleString('de-DE',{maximumFractionDigits:10,useGrouping:false})}
function add(v){if(expr==='0'&&/\d/.test(v))expr='';expr+=v;render()}
function clear(){expr='';render()}function back(){expr=expr.slice(0,-1);render()}
function tokenize(s){s=s.replace(/,/g,'.').replace(/×/g,'*').replace(/÷/g,'/').replace(/−/g,'-').replace(/π/g,'pi');const t=[],re=/\s*(sin|cos|tan|log|ln|sqrt|abs|pi|e|\d*\.?\d+|[+\-*/%()!])/gy;let i=0,m;while(i<s.length){re.lastIndex=i;m=re.exec(s);if(!m)throw Error('Syntax');t.push(m[1]);i=re.lastIndex}return t}
function calculate(s){let t=tokenize(s),p=0;const peek=()=>t[p];const eat=x=>{if(x&&peek()!==x)throw Error('Syntax');return t[p++]};
function primary(){let x=peek();if(x==='-'){eat();return -primary()}if(x==='+'){eat();return primary()}if(x==='('){eat();let v=addsub();eat(')');return v}if(['sin','cos','tan','log','ln','sqrt','abs'].includes(x)){eat();eat('(');let v=addsub();eat(')');if(x==='sin'||x==='cos'||x==='tan'){if(angle==='DEG')v=v*Math.PI/180;v=Math[x](v)}else if(x==='log')v=Math.log10(v);else if(x==='ln')v=Math.log(v);else if(x==='sqrt')v=Math.sqrt(v);else v=Math.abs(v);return v}if(x==='pi'){eat();return Math.PI}if(x==='e'){eat();return Math.E}if(x&&/^\d/.test(x)){eat();return parseFloat(x)}throw Error('Syntax')}
function power(){let v=primary();if(peek()==='!'){eat();v=factorial(v)}return v}function mul(){let v=power();while(['*','/','%'].includes(peek())){let op=eat(),b=power();if(op==='*')v*=b;else if(op==='/')v/=b;else v%=b}return v}function addsub(){let v=mul();while(['+','-'].includes(peek())){let op=eat(),b=mul();v=op==='+'?v+b:v-b}return v}let out=addsub();if(p<t.length)throw Error('Syntax');return out}
function factorial(n){if(n<0||n>170||n%1)return NaN;let r=1;for(let i=2;i<=n;i++)r*=i;return r}
function equals(){if(!expr)return;try{let value=calculate(expr),display=format(value);history.unshift({e:expr,r:display});history=history.slice(0,20);localStorage.setItem('cool-calculator-history',JSON.stringify(history));expr=String(value);render()}catch{resultEl.textContent='Fehler'}}
function renderHistory(){if(!history.length){historyEl.innerHTML='<div class="empty-state"><span class="empty-icon">⌁</span><p>Noch keine Berechnungen.</p><small>Dein Verlauf erscheint hier automatisch.</small></div>';return}historyEl.innerHTML=history.map((h,i)=>`<div class="history-item" data-history="${i}"><div class="history-expression">${escapeHtml(h.e)}</div><div class="history-result">${escapeHtml(h.r)}</div></div>`).join('')}
function escapeHtml(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
document.querySelectorAll('[data-value]').forEach(b=>b.addEventListener('click',()=>add(b.dataset.value)));document.querySelectorAll('[data-action]').forEach(b=>b.addEventListener('click',()=>{let a=b.dataset.action;if(a==='clear')clear();if(a==='backspace')back();if(a==='equals')equals();if(a==='memory-clear'){memory=0;render()}if(a==='memory-recall')add(String(memory));if(a==='memory-add'){try{memory+=calculate(expr||'0')}catch{}render()}if(a==='memory-subtract'){try{memory-=calculate(expr||'0')}catch{}render()}}));
$('#clearHistory').onclick=()=>{history=[];localStorage.removeItem('cool-calculator-history');render()};historyEl.onclick=e=>{let item=e.target.closest('[data-history]');if(item){expr=history[item.dataset.history].e;render()}};$('#angleToggle').onclick=()=>{angle=angle==='DEG'?'RAD':'DEG';$('#angleToggle').textContent=angle;render()};$('#themeToggle').onclick=()=>{document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'':'dark';localStorage.setItem('cool-calculator-theme',document.documentElement.dataset.theme)};if(localStorage.getItem('cool-calculator-theme'))document.documentElement.dataset.theme=localStorage.getItem('cool-calculator-theme');
document.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key==='='){e.preventDefault();equals()}else if(e.key==='Escape')clear();else if(e.key==='Backspace')back();else if(/[0-9.+\-*/%()]/.test(e.key))add(e.key.replace('*','×').replace('/','÷').replace('-','−'));});render();
